### ISSUE TITLE
/piyo on

### ISSUE THREAD

**Issue by Chicadaa** [IndonesianDev/whatsapp-bot#11]
misi kak, kalau aku ketik /piyo on kok error ya?, apa api key nya berbayar?,

"[EXEC] 17/03/21 22:11:33 piyo [1] from Type Your Name Here                                                              
[EROR] TypeError: piyo.indexOf is not a function at HandleMsg (C:\Users\Administrator\Documents\bot\whatsapp-bot\HandleMsg.js:3917:21 at processTicksAndRejections (internal/process/task_queues.js:97:5) "

**Comment by AlvioAdjiJanuar** [comment]
bentar saya cek ya kak

**Comment by AlvioAdjiJanuar** [comment]
Coba Install Ulang kak
saya sudah perbarui

**Comment by AlvioAdjiJanuar** [comment]
Saya close yo
