### ISSUE TITLE
createcode is not function

### ISSUE THREAD

**Issue by Fucksociety666** [IndonesianDev/whatsapp-bot#12]
![image](https://user-images.githubusercontent.com/74858900/114344180-df3cf300-9b4e-11eb-8eee-b8b5e8232c75.png)
![image](https://user-images.githubusercontent.com/74858900/114344202-ea901e80-9b4e-11eb-8ca4-41c3c1cec4d7.png)

**Comment by Fucksociety666** [comment]
> ![image](https://user-images.githubusercontent.com/74858900/114344180-df3cf300-9b4e-11eb-8eee-b8b5e8232c75.png)
> ![image](https://user-images.githubusercontent.com/74858900/114344202-ea901e80-9b4e-11eb-8ca4-41c3c1cec4d7.png)

yg /lib/codexx (dh gw isi)

**Comment by AlvioAdjiJanuar** [comment]
taruh di index.js aja

**Comment by Fucksociety666** [comment]
> taruh di index.js aja

![image](https://user-images.githubusercontent.com/74858900/114368579-115d4d80-9b6d-11eb-8165-9d416c761fbe.png)
![image](https://user-images.githubusercontent.com/74858900/114368637-1d490f80-9b6d-11eb-916c-9cc42787adb3.png)
thanks bruh
