### ISSUE TITLE
Yang mau nanya sesuatu Komen aja dibawah ya

### ISSUE THREAD

**Issue by AlvioAdjiJanuar** [IndonesianDev/whatsapp-bot#14]

**Comment by davidsky23** [comment]
√ Browser Launched
stak disini knapa ya?

**Comment by xaryow** [comment]
biar gak otomatis rubah foto jadi sticker gimana ya gan? soalnya agak ngeganggu gitu kalau ada yg ngirim foto di grup tiba tiba jadi sticker

**Comment by AlvioAdjiJanuar** [comment]
Okey nanti saya fix

**Comment by Reyzeus** [comment]
node:7174) UnhandledPromiseRejectionWarning: TypeError: messageLog is not a function
    at /root/wa1/index.js:129:9
    at Client.<anonymous> (/root/wa1/node_modules/@open-wa/wa-automate/dist/api/Client.js:542:92)
    at Generator.next (<anonymous>)
    at fulfilled (/root/wa1/node_modules/@open-wa/wa-automate/dist/api/Client.js:24:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7174) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).

**Comment by AlvioAdjiJanuar** [comment]
> node:7174) UnhandledPromiseRejectionWarning: TypeError: messageLog is not a function
> at /root/wa1/index.js:129:9
> at Client. (/root/wa1/node_modules/@open-wa/wa-automate/dist/api/Client.js:542:92)
> at Generator.next ()
> at fulfilled (/root/wa1/node_modules/@open-wa/wa-automate/dist/api/Client.js:24:58)
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:7174) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).

Udah ane fix

**Comment by AlvioAdjiJanuar** [comment]
yyyy
