### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by Crownss** [IndonesianDev/whatsapp-bot#17]
after installing all depedencies, i get this message

✓ Version: 4.20.1
[:] Database loaded.

and now what should i do ?

**Comment by mioscape** [comment]
Install Google Chrome instead using Chromium

**Comment by AlvioAdjiJanuar** [comment]
> Install Google Chrome instead using Chromium

why ?

**Comment by mioscape** [comment]
> > Install Google Chrome instead using Chromium
> 
> why ?

Its common problem in linux

**Comment by Crownss** [comment]
> Install Google Chrome instead using Chromium

do you have a reason why should i install chrome instead chromium ?

**Comment by mioscape** [comment]
> do you have a reason why should i install chrome instead chromium ?

Another repo of Wa-Bot also reffering that bug, and installing Google Chrome fix that bug.
https://github.com/YogaSakti/imageToSticker#troubleshooting

**Comment by mioscape** [comment]
> do you have a reason why should i install chrome instead chromium ?

Its also fix my bug ¯\_(ツ)_/¯

**Comment by Crownss** [comment]
> > do you have a reason why should i install chrome instead chromium ?
> 
> Another repo of Wa-Bot also reffering that bug, and installing Google Chrome fix that bug.
> https://github.com/YogaSakti/imageToSticker#troubleshooting

ok thx i'll try
