### ISSUE TITLE
Tidak bisa npm install

### ISSUE THREAD

**Issue by revansyahallam** [IndonesianDev/whatsapp-bot#5]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: whatsapp-bot@2.0.0
npm ERR! Found: sharp@0.26.3
npm ERR! node_modules/sharp
npm ERR!   sharp@"^0.26.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer sharp@"^0.27.0" from @open-wa/wa-automate@3.4.1
npm ERR! node_modules/@open-wa/wa-automate
npm ERR!   @open-wa/wa-automate@"^3.1.13" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/htm8/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/htm8/.npm/_logs/2021-02-12T23_06_27_472Z-debug.log

**Comment by AlvioAdjiJanuar** [comment]
Coba npm install sharp
