### ISSUE TITLE
Cara add prem

### ISSUE THREAD

**Issue by raooyz** [IndonesianDev/whatsapp-bot#6]
Cara add premium gimana bang commandnya? [ /premium nomerwa ] balesannya format salah mulu

**Comment by AlvioAdjiJanuar** [comment]
/premium add tagorang/6261268250150 harinya , misal harinya 30 hari berarti /premium add 616482148284 30d

**Comment by AlvioAdjiJanuar** [comment]
> Cara add premium gimana bang commandnya? [ /premium nomerwa ] balesannya format salah mulu

/premium add tagorang/6261268250150 harinya , misal harinya 30 hari berarti /premium add 616482148284 30d

**Comment by raooyz** [comment]
Oke bang makasi^^
